In [2]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import RandomizedSearchCV

In [3]:
features = pd.read_excel(r'E:\\hackstat final round\\Variables Finalized - Insurance.xlsx')
trainset = pd.read_excel(r'E:\\hackstat final round\\insurance_syn_hackathon_phase1.xlsx')

In [4]:
print(features.shape)
features

(21, 2)

,Feature,Feature Description
0,ID,Record Identifier
1,TENURE_QUINTILES,Quintiles of policy tenure (snapshot date - co...
2,payment_pr1q_mean_diff_days,Average number of days between due and paid da...
3,payment_pr1q_num_payments,Number of payments in the past three months fr...
4,FUND_VALUE2,Fund value
5,Mode_Month,Payment frequency is monthly (0/1)
6,payment_pr1q_med_diff_days,Median of number of days between due and paid ...
7,payment_pr1q_sd_diff_days,Standard deviation of number of days between d...
8,payment_pr1q_num_past_due,Number of past-due payments in the past three ...
9,payment_pr1q_num_past_due_30d,Number of >30 days past-due payments in the pa...
10,Mode_Annual,Payment frequency is annual (0/1)
11,COMMENCEMENT_MONTH,The month the policy commenced
12,payment_pr1q_sd_pay_amt,Standard deviation of payment amounts in the p...
13,ABC_ANNUAL_PREMIUM2,Annual premium
14,Mode_Quarter,Payment frequency is quarterly (0/1)
15,age,Customer age
16,payment_pr1q_sd_pay_date,Standard deviation of payment date in the past...
17,NO_OF_CHILDREN2,Number of children the customer has
18,TERM,Policy term
19,Mode_Half,Payment frequency is half yearly (0/1)
20,lapse_var,Lapsed or not - The response which needs to be...

In [5]:
tenture_dummies = pd.get_dummies(trainset['TENURE_QUINTILES'])
tenture_dummies = tenture_dummies.rename(columns={0: "TENURE_QUINTILES_0", 1: "TENURE_QUINTILES_1", 2:"TENURE_QUINTILES_2", 3:"TENURE_QUINTILES_3"})
tenture_dummies

,TENURE_QUINTILES_0,TENURE_QUINTILES_1,TENURE_QUINTILES_2,TENURE_QUINTILES_3
0,0,1,0,0
1,0,0,1,0
2,0,0,1,0
3,1,0,0,0
4,1,0,0,0
5,0,0,1,0
6,0,0,1,0
7,0,1,0,0
8,1,0,0,0
9,0,1,0,0
10,0,1,0,0
11,0,1,0,0
12,1,0,0,0
13,1,0,0,0
14,1,0,0,0
15,1,0,0,0
16,1,0,0,0
17,0,0,1,0
18,1,0,0,0
19,0,1,0,0
20,1,0,0,0
21,1,0,0,0
22,0,1,0,0
23,0,0,0,1
24,0,0,1,0
25,0,1,0,0
26,0,1,0,0
27,0,0,0,1
28,1,0,0,0
29,1,0,0,0
...,...,...,...,...
59977,0,1,0,0
59978,1,0,0,0
59979,1,0,0,0
59980,0,0,0,1
59981,1,0,0,0
59982,0,0,1,0
59983,1,0,0,0
59984,0,0,0,1
59985,0,0,0,1
59986,1,0,0,0
59987,1,0,0,0
59988,0,0,1,0
59989,1,0,0,0
59990,1,0,0,0
59991,0,0,1,0
59992,0,1,0,0
59993,1,0,0,0
59994,1,0,0,0
59995,1,0,0,0
59996,0,0,1,0
59997,1,0,0,0
59998,0,0,1,0
59999,0,0,0,1
60000,0,1,0,0
60001,0,1,0,0
60002,0,1,0,0
60003,0,0,0,1
60004,1,0,0,0
60005,0,1,0,0
60006,0,0,1,0

In [6]:
COMMENCEMENT_MONTH_dummies = pd.get_dummies(trainset['COMMENCEMENT_MONTH'])
COMMENCEMENT_MONTH_dummies = COMMENCEMENT_MONTH_dummies.rename(columns={1: "Jan", 2: "Feb", 3:"Mar", 4:"Apr", 5:"May", 6: "Jun", 7:"Jul", 8:"Aug", 9:"Sep", 10:"Oct", 11: "Nov", 12:"Dec"})
COMMENCEMENT_MONTH_dummies

       Jan  Feb  Mar  Apr  May  Jun  Jul  Aug  Sep  Oct  Nov  Dec
0        0    0    0    0    1    0    0    0    0    0    0    0
1        0    0    1    0    0    0    0    0    0    0    0    0
2        1    0    0    0    0    0    0    0    0    0    0    0
3        0    0    1    0    0    0    0    0    0    0    0    0
4        0    0    0    0    0    0    0    0    1    0    0    0
5        0    0    0    0    0    0    0    0    1    0    0    0
6        0    0    0    0    0    0    0    0    1    0    0    0
7        0    0    0    0    1    0    0    0    0    0    0    0
8        0    0    1    0    0    0    0    0    0    0    0    0
9        0    0    1    0    0    0    0    0    0    0    0    0
10       1    0    0    0    0    0    0    0    0    0    0    0
11       0    0    0    0    1    0    0    0    0    0    0    0
12       0    0    0    0    1    0    0    0    0    0    0    0
13       0    0    0    0    0    0    0    0    1    0    0    0
14       0    0    0    0    0    0    0    0    0    0    0    1
15       0    0    0    0    0    0    0    0    1    0    0    0
16       0    1    0    0    0    0    0    0    0    0    0    0
17       0    0    0    0    0    0    0    0    0    0    1    0
18       0    0    0    0    0    0    1    0    0    0    0    0
19       0    0    0    0    0    0    1    0    0    0    0    0
20       0    0    0    0    0    0    0    1    0    0    0    0
21       0    0    0    0    0    0    0    0    0    0    1    0
22       0    0    0    0    0    0    0    0    1    0    0    0
23       0    0    0    0    0    0    0    1    0    0    0    0
24       0    0    0    0    0    0    1    0    0    0    0    0
25       1    0    0    0    0    0    0    0    0    0    0    0
26       0    0    0    0    1    0    0    0    0    0    0    0
27       0    0    0    0    0    0    1    0    0    0    0    0
28       0    0    0    0    0    0    0    0    0    1    0    0
29       0    0    0    0    0    0    0    0    0    0    1    0
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
59977    0    0    0    0    0    0    0    0    0    0    1    0
59978    0    0    1    0    0    0    0    0    0    0    0    0
59979    0    0    0    0    0    0    0    0    0    1    0    0
59980    0    0    0    0    0    0    0    1    0    0    0    0
59981    0    0    0    0    0    0    0    0    1    0    0    0
59982    0    0    0    0    0    0    0    0    1    0    0    0
59983    0    1    0    0    0    0    0    0    0    0    0    0
59984    0    0    1    0    0    0    0    0    0    0    0    0
59985    0    0    0    1    0    0    0    0    0    0    0    0
59986    0    0    0    0    0    0    0    0    0    0    0    1
59987    0    0    0    0    0    1    0    0    0    0    0    0
59988    0    0    1    0    0    0    0    0    0    0    0    0
59989    0    0    0    0    0    0    0    0    1    0    0    0
59990    0    0    0    0    0    0    0    0    0    0    1    0
59991    0    0    0    0    0    0    0    0    0    0    0    1
59992    0    0    0    0    0    0    0    0    0    0    0    1
59993    0    0    0    0    0    0    1    0    0    0    0    0
59994    0    0    0    0    0    0    0    1    0    0    0    0
59995    0    1    0    0    0    0    0    0    0    0    0    0
59996    0    0    0    0    0    0    0    0    1    0    0    0
59997    0    0    0    0    1    0    0    0    0    0    0    0
59998    0    1    0    0    0    0    0    0    0    0    0    0
59999    0    0    1    0    0    0    0    0    0    0    0    0
60000    0    0    0    1    0    0    0    0    0    0    0    0
60001    0    0    0    0    0    0    0    1    0    0    0    0
60002    0    1    0    0    0    0    0    0    0    0    0    0
60003    0    0    0    0    0    1    0    0    0    0    0    0
60004    0    0    0    1    0    0    0    0    0    0    0    0
60005    0    0    0    0    0    0    0    0    1    0    0    0
60006    0    0    0    0    0    0    0    0    0    0    0    1

[60007 rows x 12 columns]

In [7]:
to_predict_age_set = pd.concat([tenture_dummies,COMMENCEMENT_MONTH_dummies,trainset['lapse_var'],trainset['age']], axis = 1) 
to_predict_age_set

,TENURE_QUINTILES_0,TENURE_QUINTILES_1,TENURE_QUINTILES_2,TENURE_QUINTILES_3,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec,lapse_var,age
0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,59.703765
1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,49.183609
2,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,46.821003
3,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,29.872764
4,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,36.998385
5,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,43.411640
6,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,29.869986
7,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,40.521141
8,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,49.903423
9,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,20.046795
10,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,32.975487
11,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,18.180586
12,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,41.041206
13,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,50.835487
14,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,34.782091
15,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,58.417643
16,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,30.164664
17,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,32.962228
18,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,38.834265
19,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,18.659898
20,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,38.895072
21,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,23.715277
22,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,39.183818
23,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,26.295555
24,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,37.118971
25,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,38.856914
26,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,25.962399
27,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,35.515671
28,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,37.782867
29,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,54.697672
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59977,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,24.381448
59978,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,53.609148
59979,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,35.565897
59980,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,49.859460
59981,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,42.213677
59982,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,46.701641
59983,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,48.309178
59984,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,35.453005
59985,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,43.069188
59986,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,43.083665
59987,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,43.924002
59988,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,60.884361
59989,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,38.311313
59990,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,29.671245
59991,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,38.128805
59992,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,33.845636
59993,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,60.472659
59994,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,43.145554
59995,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,41.391584
59996,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,39.027443
59997,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,47.944483
59998,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,40.626519
59999,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,41.265777
60000,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,46.208593
60001,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,35.685436
60002,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,29.838690
60003,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,48.442519
60004,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,61.568204
60005,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,39.878620
60006,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,30.886587

In [8]:
to_predict_age_train = to_predict_age_set[(to_predict_age_set >= 0).all(1)]
to_predict_age_train

,TENURE_QUINTILES_0,TENURE_QUINTILES_1,TENURE_QUINTILES_2,TENURE_QUINTILES_3,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec,lapse_var,age
0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,59.703765
1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,49.183609
2,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,46.821003
3,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,29.872764
4,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,36.998385
5,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,43.411640
6,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,29.869986
7,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,40.521141
8,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,49.903423
9,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,20.046795
10,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,32.975487
11,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,18.180586
12,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,41.041206
13,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,50.835487
14,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,34.782091
15,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,58.417643
16,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,30.164664
17,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,32.962228
18,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,38.834265
19,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,18.659898
20,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,38.895072
21,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,23.715277
22,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,39.183818
23,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,26.295555
24,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,37.118971
25,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,38.856914
26,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,25.962399
27,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,35.515671
28,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,37.782867
29,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,54.697672
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59977,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,24.381448
59978,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,53.609148
59979,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,35.565897
59980,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,49.859460
59981,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,42.213677
59982,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,46.701641
59983,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,48.309178
59984,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,35.453005
59985,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,43.069188
59986,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,43.083665
59987,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,43.924002
59988,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,60.884361
59989,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,38.311313
59990,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,29.671245
59991,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,38.128805
59992,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,33.845636
59993,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,60.472659
59994,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,43.145554
59995,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,41.391584
59996,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,39.027443
59997,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,47.944483
59998,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,40.626519
59999,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,41.265777
60000,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,46.208593
60001,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,35.685436
60002,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,29.838690
60003,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,48.442519
60004,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,61.568204
60005,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,39.878620
60006,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,30.886587

In [9]:
to_predict_age_test = to_predict_age_set[(to_predict_age_set['age'] < 0)]
to_predict_age_test

,TENURE_QUINTILES_0,TENURE_QUINTILES_1,TENURE_QUINTILES_2,TENURE_QUINTILES_3,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec,lapse_var,age
49153,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,-3.233938

In [10]:
age_regressor = RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=2,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=3,
           min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=None,
           oob_score=False, random_state=0, verbose=0, warm_start=False)
age_regressor.fit(to_predict_age_train.iloc[:,:17],to_predict_age_train['age'])
age_predict = age_regressor.predict(to_predict_age_test.iloc[:,:17])
print(age_predict)

[40.13417198]

In [11]:
to_predict_age_test.iloc[:,:17]

,TENURE_QUINTILES_0,TENURE_QUINTILES_1,TENURE_QUINTILES_2,TENURE_QUINTILES_3,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec,lapse_var
49153,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0

In [12]:
to_predict_age_set = to_predict_age_set.replace(-3.233937825,40.13417198)
to_predict_age_set

,TENURE_QUINTILES_0,TENURE_QUINTILES_1,TENURE_QUINTILES_2,TENURE_QUINTILES_3,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec,lapse_var,age
0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,59.703765
1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,49.183609
2,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,46.821003
3,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,29.872764
4,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,36.998385
5,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,43.411640
6,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,29.869986
7,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,40.521141
8,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,49.903423
9,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,20.046795
10,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,32.975487
11,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,18.180586
12,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,41.041206
13,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,50.835487
14,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,34.782091
15,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,58.417643
16,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,30.164664
17,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,32.962228
18,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,38.834265
19,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,18.659898
20,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,38.895072
21,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,23.715277
22,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,39.183818
23,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,26.295555
24,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,37.118971
25,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,38.856914
26,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,25.962399
27,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,35.515671
28,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,37.782867
29,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,54.697672
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59977,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,24.381448
59978,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,53.609148
59979,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,35.565897
59980,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,49.859460
59981,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,42.213677
59982,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,46.701641
59983,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,48.309178
59984,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,35.453005
59985,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,43.069188
59986,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,43.083665
59987,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,43.924002
59988,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,60.884361
59989,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,38.311313
59990,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,29.671245
59991,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,38.128805
59992,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,33.845636
59993,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,60.472659
59994,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,43.145554
59995,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,41.391584
59996,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,39.027443
59997,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,47.944483
59998,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,40.626519
59999,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,41.265777
60000,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,46.208593
60001,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,35.685436
60002,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,29.838690
60003,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,48.442519
60004,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,61.568204
60005,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,39.878620
60006,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,30.886587

In [13]:
to_predict_term_set = pd.concat([trainset['ID'],to_predict_age_set,trainset['TERM']], axis = 1)

In [14]:
to_predict_term_set

,ID,TENURE_QUINTILES_0,TENURE_QUINTILES_1,TENURE_QUINTILES_2,TENURE_QUINTILES_3,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec,lapse_var,age,TERM
0,1,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,59.703765,13.533617
1,2,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,49.183609,13.750541
2,3,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,46.821003,21.999173
3,4,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,29.872764,24.802638
4,5,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,36.998385,15.552943
5,6,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,43.411640,16.979481
6,7,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,29.869986,12.062683
7,8,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,40.521141,17.893648
8,9,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,49.903423,19.730852
9,10,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,20.046795,10.541625
10,11,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,32.975487,11.723769
11,12,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,18.180586,23.248342
12,13,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,41.041206,18.403256
13,14,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,50.835487,17.009434
14,15,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,34.782091,21.930522
15,16,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,58.417643,25.531463
16,17,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,30.164664,13.295989
17,18,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,32.962228,11.405538
18,19,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,38.834265,13.467649
19,20,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,18.659898,18.363242
20,21,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,38.895072,18.775930
21,22,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,23.715277,19.795418
22,23,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,39.183818,21.717606
23,24,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,26.295555,18.919424
24,25,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,37.118971,23.026416
25,26,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,38.856914,25.501479
26,27,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,25.962399,15.788932
27,28,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,35.515671,17.088916
28,29,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,37.782867,21.073432
29,30,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,54.697672,15.645936
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59977,59978,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,24.381448,14.952430
59978,59979,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,53.609148,15.781373
59979,59980,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,35.565897,9.599621
59980,59981,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,49.859460,29.972451
59981,59982,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,42.213677,23.554818
59982,59983,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,46.701641,17.400945
59983,59984,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,48.309178,15.721349
59984,59985,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,35.453005,15.462049
59985,59986,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,43.069188,14.739945
59986,59987,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,43.083665,18.455844
59987,59988,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,43.924002,16.484329
59988,59989,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,60.884361,18.237532
59989,59990,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,38.311313,19.648063
59990,59991,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,29.671245,22.320936
59991,59992,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,38.128805,28.415436
59992,59993,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,33.845636,11.951274
59993,59994,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,60.472659,12.923329
59994,59995,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,43.145554,20.965660
59995,59996,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,41.391584,20.717702
59996,59997,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,39.027443,15.490890
59997,59998,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,47.944483,23.049388
59998,59999,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,40.626519,17.391198
59999,60000,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,41.265777,16.675118
60000,60001,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,46.208593,16.960490
60001,60002,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,35.685436,20.393614
60002,60003,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,29.838690,21.835799
60003,60004,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,48.442519,18.919716
60004,60005,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,61.568204,34.112120
60005,60006,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,39.878620,20.903099
60006,60007,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,30.886587,18.857069

In [15]:
to_predict_term_set = to_predict_term_set.sort_values(by=['TERM'] ,ascending=False)
to_predict_term_set

,ID,TENURE_QUINTILES_0,TENURE_QUINTILES_1,TENURE_QUINTILES_2,TENURE_QUINTILES_3,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec,lapse_var,age,TERM
25067,25068,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,41.872025,37.865735
25207,25208,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,40.787574,36.985427
55747,55748,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,49.547055,36.943550
29497,29498,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,38.780829,36.594508
1732,1733,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,36.253734,36.169877
20181,20182,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,34.251529,35.369612
5303,5304,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,62.270606,34.959543
2955,2956,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,38.736218,34.865627
24737,24738,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,27.433752,34.756588
47026,47027,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,49.491930,34.698975
6819,6820,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,24.171630,34.593500
28306,28307,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,43.053974,34.407531
33540,33541,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,48.576899,34.254239
14073,14074,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,32.177098,34.249540
30245,30246,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,44.279466,34.226828
29399,29400,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,64.110457,34.178643
34883,34884,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,28.494676,34.156280
43225,43226,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,52.029742,34.149402
60004,60005,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,61.568204,34.112120
47422,47423,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,44.880318,34.011932
9460,9461,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,46.127542,33.966465
23626,23627,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,34.802092,33.725048
35436,35437,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,43.399040,33.691424
33659,33660,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,20.438613,33.686115
16814,16815,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,50.393554,33.677526
32271,32272,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,62.094816,33.643197
39928,39929,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,41.041769,33.592171
30547,30548,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,49.528201,33.575560
19779,19780,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,27.333283,33.560291
27144,27145,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,45.809921,33.551537
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38030,38031,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,41.760053,2.400274
33019,33020,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,30.077941,2.386843
56959,56960,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,35.596834,2.332888
47388,47389,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,36.573055,2.279415
20724,20725,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,36.069884,2.229748
8748,8749,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,35.676021,2.223917
57454,57455,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,48.032476,2.181671
11333,11334,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,43.006160,2.146221
42315,42316,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,37.784239,2.129997
55238,55239,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,35.675799,2.128611
47162,47163,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,37.237684,2.074750
53579,53580,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,47.856104,1.999289
48908,48909,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,37.624032,1.974920
41694,41695,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,42.454113,1.679161
11614,11615,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,36.252277,1.602557
1443,1444,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,44.177948,1.548116
29649,29650,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,34.290895,1.525755
49030,49031,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,54.586825,1.492528
10723,10724,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,46.024375,1.328999
55672,55673,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,37.581717,1.312482
17551,17552,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,40.264666,1.260066
48522,48523,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,38.750910,1.227364
23436,23437,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,40.544824,1.148306
419,420,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,30.737982,1.147383
11772,11773,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,39.220121,0.891743
40472,40473,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,46.708640,0.736267
10504,10505,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,66.621676,0.429468
33404,33405,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,48.147405,0.152490
678,679,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,47.101336,-1.694713
51913,51914,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,11.996785,-3.101329

In [16]:
to_predict_term_train = to_predict_term_set.iloc[:60005, :]
to_predict_term_test = to_predict_term_set.iloc[60005:, :]
to_predict_term_train
to_predict_term_test

,ID,TENURE_QUINTILES_0,TENURE_QUINTILES_1,TENURE_QUINTILES_2,TENURE_QUINTILES_3,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec,lapse_var,age,TERM
678,679,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,47.101336,-1.694713
51913,51914,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,11.996785,-3.101329

In [17]:
to_predict_term_train.iloc[:,1:19]

,TENURE_QUINTILES_0,TENURE_QUINTILES_1,TENURE_QUINTILES_2,TENURE_QUINTILES_3,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec,lapse_var,age
25067,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,41.872025
25207,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,40.787574
55747,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,49.547055
29497,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,38.780829
1732,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,36.253734
20181,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,34.251529
5303,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,62.270606
2955,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,38.736218
24737,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,27.433752
47026,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,49.491930
6819,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,24.171630
28306,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,43.053974
33540,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,48.576899
14073,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,32.177098
30245,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,44.279466
29399,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,64.110457
34883,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,28.494676
43225,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,52.029742
60004,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,61.568204
47422,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,44.880318
9460,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,46.127542
23626,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,34.802092
35436,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,43.399040
33659,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,20.438613
16814,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,50.393554
32271,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,62.094816
39928,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,41.041769
30547,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,49.528201
19779,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,27.333283
27144,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,45.809921
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25295,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,52.595633
9824,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,40.165884
38030,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,41.760053
33019,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,30.077941
56959,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,35.596834
47388,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,36.573055
20724,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,36.069884
8748,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,35.676021
57454,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,48.032476
11333,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,43.006160
42315,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,37.784239
55238,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,35.675799
47162,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,37.237684
53579,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,47.856104
48908,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,37.624032
41694,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,42.454113
11614,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,36.252277
1443,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,44.177948
29649,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,34.290895
49030,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,54.586825
10723,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,46.024375
55672,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,37.581717
17551,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,40.264666
48522,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,38.750910
23436,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,40.544824
419,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,30.737982
11772,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,39.220121
40472,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,46.708640
10504,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,66.621676
33404,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,48.147405

In [18]:
# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 200, stop = 2000, num = 2)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt']
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(10, 110, num = 2)]
max_depth.append(None)
# Minimum number of samples required to split a node
min_samples_split = [2, 5, 10]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 4]
# Method of selecting samples for training each tree
bootstrap = [True, False]
# Create the random grid
random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               'bootstrap': bootstrap}
print(random_grid)

{'n_estimators': [200, 2000], 'max_features': ['auto', 'sqrt'], 'max_depth': [10, 110, None], 'min_samples_split': [2, 5, 10], 'min_samples_leaf': [1, 2, 4], 'bootstrap': [True, False]}

In [ ]:
# Use the random grid to search for best hyperparameters
# First create the base model to tune
rf = RandomForestRegressor()
# Random search of parameters, using 3 fold cross validation, 
# search across 100 different combinations, and use all available cores
rf_random = RandomizedSearchCV(estimator = rf, param_distributions = random_grid, n_iter = 100, cv = 3, verbose=2, random_state=42, n_jobs = -1)
# Fit the random search model
rf_random.fit(to_predict_term_train.iloc[:,1:19],to_predict_term_train['TERM'])

rf_random.best_params_

Fitting 3 folds for each of 100 candidates, totalling 300 fits

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.